version: '3'

services: 
  flask-app:
    build: python-app/. # name of the folder where the Dockerfile is
    container_name: flask-app # name of the container
    ports:
      - "5000:5000" # host port : container port
    volumes:
      - .:/flask/code # save data in a volume
    networks: 
      app_net:
        ipv4_address: 172.19.0.2 # ip address of the container to communicate from other containers

  node-app:
    build: javascript-app/. # name of the folder where the Dockerfile is
    container_name: node-app # name of the container
    ports:
      - "3000:3000" # host port : container port
    volumes:
      - .:/node/app # save data in a volume
    networks: 
      app_net:
        ipv4_address: 172.19.0.3 # ip address of the container to communicate from other containers

networks: # containers network to communicate between them
    app_net:
        ipam:
            driver: default
            config:
            - subnet: "172.19.0.0/24"